In [1]:
!pip install mobilechelonian

In [2]:
from mobilechelonian import Turtle

In [3]:
t=Turtle()
t.speed(5)
colours=["red","blue","yellow","brown","black","purple","green"]
#t.penup();t.left(90);t.forward(200);t.right(90);t.pendown()
#for i in range (0,18):
#   t.pencolor(colours[i%7])
#  t.right(20)
# t.forward(50)
    
#t.right(180)
#t.home()
t.pendown(); t.left(90);t.forward(15);t.right(180);t.forward(30)

Turtle()

Suma de 2 vectores

In [4]:
vector1=[2,3,4,11,13]
vector2=[5,7,8,14,15]
suma=[]
for i in range(len(vector1)):
    suma.append(vector1[i]+vector2[i])
suma

[7, 10, 12, 25, 28]

In [5]:
import numpy as np

In [6]:
x=np.array([2,1,3])
y=np.array([4,6,7])
print(x+y)

[ 6  7 10]


In [7]:
dot_product=0
for i in range(len(x)):
    dot_product=dot_product+(x[i]*y[i])
dot_product

35

In [8]:
sum(x*y)

35

In [9]:
x.dot(y)

35

In [10]:
x@y

35

In [11]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[5,4,6],[7,2,1],[5,2,9]])
print(A)
print(B)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 4 6]
 [7 2 1]
 [5 2 9]]


In [12]:
A+B

array([[ 6,  6,  9],
       [11,  7,  7],
       [12, 10, 18]])

In [13]:
A*B
#elemento a elemento

array([[ 5,  8, 18],
       [28, 10,  6],
       [35, 16, 81]])

In [14]:
A@B
#producto punto

array([[ 34,  14,  35],
       [ 85,  38,  83],
       [136,  62, 131]])

In [15]:
A.shape

(3, 3)

In [16]:
print (np.arange(1,10).reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Sistema de ecuaciones lineales
x+2y=1
3x+y=5

In [17]:
S=np.array([[1,-2],[3,2]])
R=np.array([[1],[11]])
X=np.linalg.inv(S)@R
X

array([[3.],
       [1.]])

In [18]:
S=np.array([[1,2,3],[2,5,2],[6,-3,1]])
R=np.array([[6],[4],[2]])
X=np.linalg.inv(S)@R
X

array([[-1.11022302e-16],
       [-6.93889390e-17],
       [ 2.00000000e+00]])